#!/usr/bin/env bash
# Write .env.development.local from `supabase status` so local npm run dev
# never mixes cloud service_role with 127.0.0.1.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/.env.development.local"

if ! command -v supabase >/dev/null 2>&1; then
  echo "FAIL: supabase CLI not found." >&2
  exit 1
fi

if ! supabase status >/dev/null 2>&1; then
  echo "FAIL: local Supabase is not running. Run: npx supabase start" >&2
  exit 1
fi

eval "$(supabase status -o env)"

cat > "$OUT" <<EOF
# Auto-generated by scripts/sync-dev-supabase-env.sh — local dev overrides cloud .env.local
# Re-run after \`supabase stop/start\` if keys change.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
EOF

echo "OK: wrote $OUT (URL=${API_URL})"
echo "Restart npm run dev if it is already running."
